version: 5.1.0
variant: default
logo: https://mapp.alicdn.com/1626189208871DQ1TndXNm17L8CA.png
head:
    favicon: /favicon.ico
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        主页: /
        归档: /archives
        关于: /about
    links: 
footer:
    links: 
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
search:
    type: insight
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: 字魂凝创
        author_title: 感受文字的力量
        avatar: https://mapp.alicdn.com/1626189208871DQ1TndXNm17L8CA.png
        avatar_rounded: false
        gravatar: 
        follow_link: https://weibo.com/u/5847570266
        social_links: 
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: recent_posts
    -
        position: left
        type: archives
plugins:
    animejs: true
    back_to_top: true
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
providers:
    cdn: unpkg
    fontcdn: ustc
    iconcdn: loli
